[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "yiuqvvn-zsb27985"
user = "cesartemp122024"
password = "&kCED5MQmz:9d:x"
